package in.nmaloth.NonAuthProcessor.model;

public enum MessageType {

    AUTH_REQUEST,
    AUTH_RESPONSE,
    AUTH_ADVICE,
    AUTH_ADVICE_RESPONSE,
    FINANCIAL_REQUEST,
    FINANCIAL_RESPONSE,
    FINANCIAL_ADVICE,
    FINANCIAL_ADVICE_RESPONSE,
    UPDATE_REQUEST_ACQUIRER,
    UPDATE_REQUEST_ISSUER,
    UPDATE_RESPONSE_ACQUIRER,
    UPDATE_RESPONSE_ISSUER,
    REVERSAL_REQUEST,
    REVERSAL_RESPONSE,
    REVERSAL_ADVICE,
    REVERSAL_ADVICE_RESPONSE,
    ADMIN_MESSAGES,
    ADMIN_MESSAGE_RESPONSE,
    ADMIN_ADVICE,
    ADMIN_ADVICE_RESPONSE,
    TOKEN_REQUEST,
    TOKEN_RESPONSE,
    TOKEN_ADVICE_REQUEST,
    TOKEN_ADVICE_RESPONSE,
    NETWORK_MESSAGE,
    NETWORK_MESSAGE_RESPONSE,
    NETWORK_ADVICE,
    NETWORK_ADVICE_RESPONSE


}
