// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OutgoingMessage.proto

package in.nmaloth.NonAuthProcessor.model.proto;

public final class OutgoingMessageOuterClass {
  private OutgoingMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OutgoingMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string messageId = 1;</code>
     * @return The messageId.
     */
    java.lang.String getMessageId();
    /**
     * <code>string messageId = 1;</code>
     * @return The bytes for messageId.
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>string messageTypeId = 2;</code>
     * @return The messageTypeId.
     */
    java.lang.String getMessageTypeId();
    /**
     * <code>string messageTypeId = 2;</code>
     * @return The bytes for messageTypeId.
     */
    com.google.protobuf.ByteString
        getMessageTypeIdBytes();

    /**
     * <code>string containerId = 3;</code>
     * @return The containerId.
     */
    java.lang.String getContainerId();
    /**
     * <code>string containerId = 3;</code>
     * @return The bytes for containerId.
     */
    com.google.protobuf.ByteString
        getContainerIdBytes();

    /**
     * <code>string channelId = 4;</code>
     * @return The channelId.
     */
    java.lang.String getChannelId();
    /**
     * <code>string channelId = 4;</code>
     * @return The bytes for channelId.
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>string aggregatorInstance = 5;</code>
     * @return The aggregatorInstance.
     */
    java.lang.String getAggregatorInstance();
    /**
     * <code>string aggregatorInstance = 5;</code>
     * @return The bytes for aggregatorInstance.
     */
    com.google.protobuf.ByteString
        getAggregatorInstanceBytes();

    /**
     * <code>bytes message = 6;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();

    /**
     * <code>optional string senderInstance = 7;</code>
     * @return Whether the senderInstance field is set.
     */
    boolean hasSenderInstance();
    /**
     * <code>optional string senderInstance = 7;</code>
     * @return The senderInstance.
     */
    java.lang.String getSenderInstance();
    /**
     * <code>optional string senderInstance = 7;</code>
     * @return The bytes for senderInstance.
     */
    com.google.protobuf.ByteString
        getSenderInstanceBytes();
  }
  /**
   * Protobuf type {@code in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessage}
   */
  public static final class OutgoingMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessage)
      OutgoingMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OutgoingMessage.newBuilder() to construct.
    private OutgoingMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OutgoingMessage() {
      messageId_ = "";
      messageTypeId_ = "";
      containerId_ = "";
      channelId_ = "";
      aggregatorInstance_ = "";
      message_ = com.google.protobuf.ByteString.EMPTY;
      senderInstance_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OutgoingMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OutgoingMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              messageTypeId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              containerId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              aggregatorInstance_ = s;
              break;
            }
            case 50: {

              message_ = input.readBytes();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              senderInstance_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage.class, in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <code>string messageId = 1;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string messageId = 1;</code>
     * @return The bytes for messageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object messageTypeId_;
    /**
     * <code>string messageTypeId = 2;</code>
     * @return The messageTypeId.
     */
    @java.lang.Override
    public java.lang.String getMessageTypeId() {
      java.lang.Object ref = messageTypeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageTypeId_ = s;
        return s;
      }
    }
    /**
     * <code>string messageTypeId = 2;</code>
     * @return The bytes for messageTypeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageTypeIdBytes() {
      java.lang.Object ref = messageTypeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTAINERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object containerId_;
    /**
     * <code>string containerId = 3;</code>
     * @return The containerId.
     */
    @java.lang.Override
    public java.lang.String getContainerId() {
      java.lang.Object ref = containerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        containerId_ = s;
        return s;
      }
    }
    /**
     * <code>string containerId = 3;</code>
     * @return The bytes for containerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContainerIdBytes() {
      java.lang.Object ref = containerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        containerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELID_FIELD_NUMBER = 4;
    private volatile java.lang.Object channelId_;
    /**
     * <code>string channelId = 4;</code>
     * @return The channelId.
     */
    @java.lang.Override
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>string channelId = 4;</code>
     * @return The bytes for channelId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGGREGATORINSTANCE_FIELD_NUMBER = 5;
    private volatile java.lang.Object aggregatorInstance_;
    /**
     * <code>string aggregatorInstance = 5;</code>
     * @return The aggregatorInstance.
     */
    @java.lang.Override
    public java.lang.String getAggregatorInstance() {
      java.lang.Object ref = aggregatorInstance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aggregatorInstance_ = s;
        return s;
      }
    }
    /**
     * <code>string aggregatorInstance = 5;</code>
     * @return The bytes for aggregatorInstance.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAggregatorInstanceBytes() {
      java.lang.Object ref = aggregatorInstance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aggregatorInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>bytes message = 6;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    public static final int SENDERINSTANCE_FIELD_NUMBER = 7;
    private volatile java.lang.Object senderInstance_;
    /**
     * <code>optional string senderInstance = 7;</code>
     * @return Whether the senderInstance field is set.
     */
    @java.lang.Override
    public boolean hasSenderInstance() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string senderInstance = 7;</code>
     * @return The senderInstance.
     */
    @java.lang.Override
    public java.lang.String getSenderInstance() {
      java.lang.Object ref = senderInstance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderInstance_ = s;
        return s;
      }
    }
    /**
     * <code>optional string senderInstance = 7;</code>
     * @return The bytes for senderInstance.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderInstanceBytes() {
      java.lang.Object ref = senderInstance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (!getMessageTypeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageTypeId_);
      }
      if (!getContainerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, containerId_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, channelId_);
      }
      if (!getAggregatorInstanceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, aggregatorInstance_);
      }
      if (!message_.isEmpty()) {
        output.writeBytes(6, message_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, senderInstance_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (!getMessageTypeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageTypeId_);
      }
      if (!getContainerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, containerId_);
      }
      if (!getChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, channelId_);
      }
      if (!getAggregatorInstanceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, aggregatorInstance_);
      }
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, message_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, senderInstance_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage)) {
        return super.equals(obj);
      }
      in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage other = (in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage) obj;

      if (!getMessageId()
          .equals(other.getMessageId())) return false;
      if (!getMessageTypeId()
          .equals(other.getMessageTypeId())) return false;
      if (!getContainerId()
          .equals(other.getContainerId())) return false;
      if (!getChannelId()
          .equals(other.getChannelId())) return false;
      if (!getAggregatorInstance()
          .equals(other.getAggregatorInstance())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (hasSenderInstance() != other.hasSenderInstance()) return false;
      if (hasSenderInstance()) {
        if (!getSenderInstance()
            .equals(other.getSenderInstance())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + MESSAGETYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageTypeId().hashCode();
      hash = (37 * hash) + CONTAINERID_FIELD_NUMBER;
      hash = (53 * hash) + getContainerId().hashCode();
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      hash = (37 * hash) + AGGREGATORINSTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getAggregatorInstance().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (hasSenderInstance()) {
        hash = (37 * hash) + SENDERINSTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getSenderInstance().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessage)
        in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage.class, in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage.Builder.class);
      }

      // Construct using in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = "";

        messageTypeId_ = "";

        containerId_ = "";

        channelId_ = "";

        aggregatorInstance_ = "";

        message_ = com.google.protobuf.ByteString.EMPTY;

        senderInstance_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_descriptor;
      }

      @java.lang.Override
      public in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage getDefaultInstanceForType() {
        return in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage.getDefaultInstance();
      }

      @java.lang.Override
      public in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage build() {
        in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage buildPartial() {
        in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage result = new in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.messageId_ = messageId_;
        result.messageTypeId_ = messageTypeId_;
        result.containerId_ = containerId_;
        result.channelId_ = channelId_;
        result.aggregatorInstance_ = aggregatorInstance_;
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderInstance_ = senderInstance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage) {
          return mergeFrom((in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage other) {
        if (other == in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getMessageTypeId().isEmpty()) {
          messageTypeId_ = other.messageTypeId_;
          onChanged();
        }
        if (!other.getContainerId().isEmpty()) {
          containerId_ = other.containerId_;
          onChanged();
        }
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (!other.getAggregatorInstance().isEmpty()) {
          aggregatorInstance_ = other.aggregatorInstance_;
          onChanged();
        }
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        if (other.hasSenderInstance()) {
          bitField0_ |= 0x00000001;
          senderInstance_ = other.senderInstance_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>string messageId = 1;</code>
       * @return The messageId.
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageId = 1;</code>
       * @return The bytes for messageId.
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageId = 1;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 1;</code>
       * @param value The bytes for messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageTypeId_ = "";
      /**
       * <code>string messageTypeId = 2;</code>
       * @return The messageTypeId.
       */
      public java.lang.String getMessageTypeId() {
        java.lang.Object ref = messageTypeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageTypeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageTypeId = 2;</code>
       * @return The bytes for messageTypeId.
       */
      public com.google.protobuf.ByteString
          getMessageTypeIdBytes() {
        java.lang.Object ref = messageTypeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageTypeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageTypeId = 2;</code>
       * @param value The messageTypeId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageTypeId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageTypeId() {
        
        messageTypeId_ = getDefaultInstance().getMessageTypeId();
        onChanged();
        return this;
      }
      /**
       * <code>string messageTypeId = 2;</code>
       * @param value The bytes for messageTypeId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageTypeId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object containerId_ = "";
      /**
       * <code>string containerId = 3;</code>
       * @return The containerId.
       */
      public java.lang.String getContainerId() {
        java.lang.Object ref = containerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          containerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string containerId = 3;</code>
       * @return The bytes for containerId.
       */
      public com.google.protobuf.ByteString
          getContainerIdBytes() {
        java.lang.Object ref = containerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          containerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string containerId = 3;</code>
       * @param value The containerId to set.
       * @return This builder for chaining.
       */
      public Builder setContainerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        containerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string containerId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContainerId() {
        
        containerId_ = getDefaultInstance().getContainerId();
        onChanged();
        return this;
      }
      /**
       * <code>string containerId = 3;</code>
       * @param value The bytes for containerId to set.
       * @return This builder for chaining.
       */
      public Builder setContainerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        containerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object channelId_ = "";
      /**
       * <code>string channelId = 4;</code>
       * @return The channelId.
       */
      public java.lang.String getChannelId() {
        java.lang.Object ref = channelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string channelId = 4;</code>
       * @return The bytes for channelId.
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        java.lang.Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channelId = 4;</code>
       * @param value The channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 4;</code>
       * @param value The bytes for channelId to set.
       * @return This builder for chaining.
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object aggregatorInstance_ = "";
      /**
       * <code>string aggregatorInstance = 5;</code>
       * @return The aggregatorInstance.
       */
      public java.lang.String getAggregatorInstance() {
        java.lang.Object ref = aggregatorInstance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          aggregatorInstance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string aggregatorInstance = 5;</code>
       * @return The bytes for aggregatorInstance.
       */
      public com.google.protobuf.ByteString
          getAggregatorInstanceBytes() {
        java.lang.Object ref = aggregatorInstance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aggregatorInstance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string aggregatorInstance = 5;</code>
       * @param value The aggregatorInstance to set.
       * @return This builder for chaining.
       */
      public Builder setAggregatorInstance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        aggregatorInstance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string aggregatorInstance = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAggregatorInstance() {
        
        aggregatorInstance_ = getDefaultInstance().getAggregatorInstance();
        onChanged();
        return this;
      }
      /**
       * <code>string aggregatorInstance = 5;</code>
       * @param value The bytes for aggregatorInstance to set.
       * @return This builder for chaining.
       */
      public Builder setAggregatorInstanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        aggregatorInstance_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes message = 6;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>bytes message = 6;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes message = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      private java.lang.Object senderInstance_ = "";
      /**
       * <code>optional string senderInstance = 7;</code>
       * @return Whether the senderInstance field is set.
       */
      public boolean hasSenderInstance() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string senderInstance = 7;</code>
       * @return The senderInstance.
       */
      public java.lang.String getSenderInstance() {
        java.lang.Object ref = senderInstance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderInstance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string senderInstance = 7;</code>
       * @return The bytes for senderInstance.
       */
      public com.google.protobuf.ByteString
          getSenderInstanceBytes() {
        java.lang.Object ref = senderInstance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderInstance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string senderInstance = 7;</code>
       * @param value The senderInstance to set.
       * @return This builder for chaining.
       */
      public Builder setSenderInstance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senderInstance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderInstance = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderInstance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderInstance_ = getDefaultInstance().getSenderInstance();
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderInstance = 7;</code>
       * @param value The bytes for senderInstance to set.
       * @return This builder for chaining.
       */
      public Builder setSenderInstanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        senderInstance_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessage)
    }

    // @@protoc_insertion_point(class_scope:in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessage)
    private static final in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage();
    }

    public static in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OutgoingMessage>
        PARSER = new com.google.protobuf.AbstractParser<OutgoingMessage>() {
      @java.lang.Override
      public OutgoingMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OutgoingMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OutgoingMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OutgoingMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public in.nmaloth.NonAuthProcessor.model.proto.OutgoingMessageOuterClass.OutgoingMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025OutgoingMessage.proto\022\'in.nmaloth.NonA" +
      "uthProcessor.model.proto\"\300\001\n\017OutgoingMes" +
      "sage\022\021\n\tmessageId\030\001 \001(\t\022\025\n\rmessageTypeId" +
      "\030\002 \001(\t\022\023\n\013containerId\030\003 \001(\t\022\021\n\tchannelId" +
      "\030\004 \001(\t\022\032\n\022aggregatorInstance\030\005 \001(\t\022\017\n\007me" +
      "ssage\030\006 \001(\014\022\033\n\016senderInstance\030\007 \001(\tH\000\210\001\001" +
      "B\021\n\017_senderInstanceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_in_nmaloth_NonAuthProcessor_model_proto_OutgoingMessage_descriptor,
        new java.lang.String[] { "MessageId", "MessageTypeId", "ContainerId", "ChannelId", "AggregatorInstance", "Message", "SenderInstance", "SenderInstance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
